name: Publish Package to npmjs
on:
  push:
    branches: [main]
    paths:
      - "apps/cli/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build CLI package
        run: pnpm --filter ./apps/cli... run build

      - name: Publish package to npm
        working-directory: apps/cli
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
