name: Publish Package to npmjs
on:
  push:
    branches: [main]
     paths:
      - 'cli/**' # Triggers the workflow only when changes are made in the 'cli' directory
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}  
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd cli && npm ci
      - run: cd cli && npm run build
      - run: cd cli && npm publish
        env:          
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}