name: Publish Package to npmjs
on:
  push:
    branches: [main]
    paths:
      - "apps/cli/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: pnpm-lock.yaml
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - run: cd apps/cli && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
